version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
     
  mariadb:
    image: 'mariadb:10'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${TYPEORM_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${TYPEORM_DATABASE}'
        MYSQL_USER: '${TYPEORM_USERNAME}'
        MYSQL_PASSWORD: '${TYPEORM_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'todo-data:/var/lib/mysql'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${TYPEORM_PASSWORD}"]
        retries: 3
        timeout: 5s"

volumes:
  todo-data:
    driver: local